[package]
name = "move-cli"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "CLI frontend for the Move compiler and VM"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
difference = "2.0.0"
include_dir = { version = "0.6.0", features = ["search"] }
once_cell = "1.7.2"
petgraph = "0.5.1"
structopt = "0.3.21"

bcs = "0.1.2"
bytecode-verifier = { path = "../../bytecode-verifier" }
diem-framework-releases = { path = "../../diem-framework/releases" }
disassembler = { path = "../disassembler" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
diem-types = { path = "../../../types" }
move-coverage = { path = "../move-coverage" }
move-core-types = { path = "../../move-core/types" }
move-lang = { path = "../../move-lang" }
move-vm-types = { path = "../../move-vm/types" }
move-vm-runtime = { path = "../../move-vm/runtime", features = ["debug_module"] }
read-write-set = { path = "../read-write-set" }
resource-viewer = { path = "../resource-viewer" }
move-binary-format = { path = "../../move-binary-format" }
vm-genesis = { path = "../vm-genesis" }
walkdir = "2.3.1"

[dev-dependencies]
datatest-stable = "0.1.1"

[[bin]]
name = "move"
path = "src/main.rs"

[[test]]
name = "cli_testsuite"
harness = false
