[package]
name = "move-vm-runtime"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Core Move execution logic"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fail = "0.4.0"
mirai-annotations = "1.10.1"
once_cell = "1.7.2"
parking_lot = "0.11.1"

bytecode-verifier = { path = "../../bytecode-verifier" }
diem-crypto = { path = "../../../crypto/crypto" }
diem-logger = { path = "../../../common/logger" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
diem-types = { path = "../../../types" }
move-core-types = { path = "../../move-core/types" }
move-vm-natives = { path = "../natives" }
move-vm-types = { path = "../types" }
move-binary-format = { path = "../../move-binary-format" }

[dev-dependencies]
anyhow = "1.0.38"
hex = "0.4.3"
proptest = "1.0.0"

compiler = { path = "../../compiler" }
move-lang = { path = "../../move-lang" }

[features]
default = []
debug_module = ["move-vm-natives/debug_module"]
fuzzing = ["move-vm-types/fuzzing"]
failpoints = ["fail/failpoints"]
