[package]
name = "move-vm-natives"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Move VM native functions"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.7.2"
mirai-annotations = "1.10.1"
sha2 = "0.9.3"
smallvec = "1.6.1"

diem-crypto = { path = "../../../crypto/crypto" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
move-core-types = { path = "../../move-core/types" }
move-vm-types = { path = "../types" }
move-binary-format = { path = "../../move-binary-format" }

[features]
default = []
debug_module = []
