[package]
name = "compiler"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem compiler"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bytecode-verifier = { path = "../bytecode-verifier" }
ir-to-bytecode = { path = "ir-to-bytecode" }
bytecode-source-map = { path = "bytecode-source-map" }
diem-framework-releases = { path = "../diem-framework/releases" }
diem-workspace-hack = { path = "../../common/workspace-hack" }
move-ir-types = { path = "../move-ir/types" }
move-core-types = { path = "../move-core/types" }
move-binary-format = { path = "../move-binary-format" }
bcs = "0.1.2"
structopt = "0.3.21"
serde_json = "1.0.64"

[features]
default = []
