[package]
name = "test-generation"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem test generation"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
rand = "0.8.3"
num_cpus = "1.13.0"
mirai-annotations = "1.10.1"
structopt = "0.3.21"
itertools = "0.10.0"
hex = "0.4.3"
getrandom = "0.2.2"
crossbeam-channel = "0.5.0"

bytecode-verifier = { path = "../../bytecode-verifier" }
diem-config = { path = "../../../config" }
diem-logger = { path = "../../../common/logger" }
diem-state-view = { path = "../../../storage/state-view" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
move-core-types = { path = "../../move-core/types" }
move-vm-runtime = { path = "../../move-vm/runtime" }
move-vm-types = { path = "../../move-vm/types" }
module-generation = { path = "../module-generation" }
move-binary-format = { path = "../../move-binary-format" }
diem-vm = { path = "../../diem-vm" }
language-e2e-tests = { path = "../e2e-tests" }
diem-types = { path = "../../../types" }

[features]
mirai-contracts = []
