name: ci-update-sccache

on:
  create:
    branches: [main, release-*, gha-test-*]
  push:
    branches: [main, release-*, gha-test-*]

defaults:
  run:
    shell: bash

env:
  max_threads: 16
  pre_command: cd /opt/git/diem/

jobs:
  update-sccache-osx:
    environment:
      name: Sccache
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # This ensures that the tip of the PR is checked out instead of the merge between the base ref and the tip
          # On `push` this value will be empty and will "do-the-right-thing"
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 #get all the history!!!
      - id: changes
        name: determine changes
        uses: diem/actions/changes@266156eaff7ba6e1253cf7019506c7b3702f73de
        with:
          workflow-file: ci-update-sccache.yml
      - id: rust-changes
        name: find rust/cargo changes.
        uses: diem/actions/matches@266156eaff7ba6e1253cf7019506c7b3702f73de
        with:
          pattern: '^documentation\|^docker\|^scripts'
          invert: "true"
      - uses: ./.github/actions/build-setup
        if: ${{ steps.rust-changes.outputs.changes-found == 'true' }}
      - uses: actions/cache@v2.1.6
        if: ${{ steps.rust-changes.outputs.changes-found == 'true' }}
        with:
          path: "/opt/cargo/git\n/opt/cargo/registry\n/opt/cargo/.package-cache"
          key: crates-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: "crates-${{ runner.os }}"
      - name: build all unit test code.
        if: ${{ steps.rust-changes.outputs.changes-found == 'true' }}
        run: |
          $pre_command && cargo x test --no-run --jobs ${max_threads} --unit
        env:
          SCCACHE_AWS_ACCESS_KEY_ID: ${{ secrets.ENV_DIEM_S3_AWS_ACCESS_KEY_ID }}
          SCCACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.ENV_DIEM_S3_AWS_SECRET_ACCESS_KEY }}
      - uses: ./.github/actions/build-teardown
        if: ${{ steps.rust-changes.outputs.changes-found == 'true' }}

  # In the future when the script can differentiate between target branches for each auto run then we'll
  # update this report to differentiate branches.
  unit-test-allure-report:
    name: Unit Test Reports
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}
    environment:
      name: Sccache
    container:
      image: diem/build_environment:main
      volumes:
        - "${{github.workspace}}:/opt/git/diem"
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # This ensures that the tip of the PR is checked out instead of the merge between the base ref and the tip
          # On `push` this value will be empty and will "do-the-right-thing"
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 #get all the history!!!
      - uses: ./.github/actions/build-setup
        # build setup is called to ensure the latest docker image tooling is in place and the ~/.profile is called.
      - name: Publish unit test results
        uses: diem/actions/process-test-results@266156eaff7ba6e1253cf7019506c7b3702f73de
        with:
          #used to read artifacts, annoying to need one.
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "unit-test-results codegen-unit-test-results"
          workflow_file: ci-test.yml
          branch: auto
          history: 20
          recreate: false
          allure_configuration: ./allure-configuration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ENV_DIEM_S3_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ENV_DIEM_S3_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.ENV_DIEM_S3_AWS_REGION }}
